services:
  redis:
    image: redis:latest
    container_name: redis-blooddonor
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
